#!/bin/bash
if lspci | grep -q "02:00.0 Signal processing controller \[1109\]: CERN/ECP/EDU Device beaf"; then
if [ -f /sys/bus/pci/devices/0000\:02\:00.0/remove ]
then
	echo "removing"
	echo 1 > /sys/bus/pci/devices/0000\:02\:00.0/remove
fi
else
echo "no decive found to remove"
fi
sleep 1
echo 1 > /sys/bus/pci/rescan
