// rorc_registers.h: RORC Register Definitions
//
// manually composed register file
// for cnet readout and flesin design
#define CNET_REG_DLM_CFG 10
#define CNET_REG_GTX_DATAPATH_STS 1
#define CNET_REG_GTX_MC_GEN_CFG 2
#define CNET_REG_GTX_PENDING_MC_L 3
#define CNET_REG_GTX_PENDING_MC_H 4
#define CNET_REG_GTX_CTRL_TX 5
#define CNET_REG_GTX_CTRL_RX 6
#define CNET_REG_GTX_DLM 7
#define CNET_REG_GTX_MC_GEN_CFG_HDR 8
#define CNET_REG_GTX_MC_GEN_CFG_IDX_L 9
#define CNET_REG_GTX_MC_GEN_CFG_IDX_H 10
#define CNET_REG_GTX_MC_INDEX_L 11
#define CNET_REG_GTX_MC_INDEX_H 12
#define CNET_MEM_BASE_CTRL_TX 16
#define CNET_MEM_SIZE_CTRL_TX 16
#define CNET_MEM_BASE_CTRL_RX 32
#define CNET_MEM_SIZE_CTRL_RX 16
#define CNET_REG_GTX_DIAG_PCS_STARTUP 48
#define CNET_REG_GTX_DIAG_EBTB_CODE_ERR 49
#define CNET_REG_GTX_DIAG_EBTB_DISP_ERR 50
#define CNET_REG_GTX_DIAG_CRC_ERROR 51
#define CNET_REG_GTX_DIAG_PACKET 52
#define CNET_REG_GTX_DIAG_PACKET_ERR 53
#define CNET_REG_GTX_DIAG_FLAGS 54
#define CNET_REG_GTX_DIAG_CLEAR 55
