#!/bin/bash

shopt -u nocaseglob
LANG=C

clang-format-3.4 -i \
  [A-Z]*.hpp \
  include.hpp \
  fles_ipc.hpp \
  concurrent_queue.hpp \
  global.hpp \
  main.cpp \
  pattern-check.cpp \
  raw-storage.cpp
