#!/bin/bash

shopt -u nocaseglob
LANG=C

clang-format-3.8 -i lib/flib/*.[hc]*
clang-format-3.8 -i lib/flib_ipc/*.[hc]*
clang-format-3.8 -i lib/pda/*.[hc]*
clang-format-3.8 -i app/flib_server/*.[hc]*
clang-format-3.8 -i app/flib_cfg/*.[hc]*
clang-format-3.8 -i app/flib_tools/*.[hc]*
