#!/bin/bash

set -e
shopt -u nocaseglob
LANG=C

DIR="$(git rev-parse --show-toplevel)"
cd "$DIR"

clang-format -style=file -fallback-style=none -i \
  lib/fles_core/*.[hc]pp \
  app/{flesnet,tsclient}/*.[hc]pp
