#!/bin/bash

# 2014-11-24 Dirk Hutter

# Checks that can be performed before flesnet start 
# to make sure everything is in a proper state

function check_mem {
    FREEMEM=`cat /proc/meminfo | grep MemFree | awk '{ print $2 }'`
    if [ $1 -gt $FREEMEM ]; then
	echo ERROR: not enough memory: asked $1 kB avail $FREEMEM kB
    else
	echo INFO: $FREEMEM kB memory available
    fi
}


function check_is_not_running {
    ps caux | grep -v $$ | grep $1 > /dev/null
    if [ $? -eq 0 ]; then
	echo "ERROR: an instance of $1 is already running."
	exit 1
    else
	echo -e "INFO: $1 is not running."
    fi
}


function check_is_running {
    ps caux | grep -v $$ | grep $1 > /dev/null
    if [ $? -eq 0 ]; then
	echo -e "INFO: $1 is running."
    else
	echo "ERROR: no instance of $1 is running."
	exit 1
    fi
}


function check_no_params_flib_ctrl {
    FLIB_CTRL_CHECK_OPT=`ps aux | grep flib_ctrl | grep -v grep | grep "ctrl -"`
    if [ $? -eq 0 ]; then
	echo "ERROR: flib_ctrl is running with command line options."
	echo exiting ...
	exit 1
    fi
}

function check_shm {
    ls /dev/shm/flesnet* > /dev/null 2>&1
    if [ $? -eq 0 ]; then
	echo -e "ERROR: shared memory left. Run flesnet-cleanup."
	exit 1
    else
	echo "INFO: no shard memory left."
    fi
}
