#!/bin/bash
# 2014, Dirk Hutter <hutter@compeng.uni-frankfurt.de>

# cleanup script for flib readout

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/check_functions

list_dma_buffers $(find_devices)
free_dma_buffers $(find_devices)

killall -9 mstool
killall -9 flesnet
killall -9 tsclient

# from readout
rm /dev/shm/shm_flesnet*
rm /dev/shm/shm_server*

# from flesctl
#rm /dev/shm/flesnet*
#rm /dev/shm/flib_server*

#echo "Please reconfigure FPGA"
