#!/bin/bash
# 2013, Jan de Cuveland <cuveland@compeng.uni-frankfurt.de>
# 2013, Dirk Hutter <hutter@compeng.uni-frankfurt.de>

set -e
# Vivado only supports remote program with ESN

### user configuration ###

# Add Xilinx cable serial number if more than one Xilinx-Cable is connected
ESN=

# Choose type of cable in case of vivado
# valid options (case sensitive): Xilinx, Digilent
CABLE_TYPE=Digilent

# Add full path to impact/vivado if Xilinx directory is not in PATH
IMPACT=impact
VIVADO=vivado

# FLIB PCI device
# set to FLIB pci device identifyer, i.g. 01:00.0
# in order to handle a spacific FLIB.
# If empty all FLIBs will be reinitialized on PCI
PCI_DEV=

# CSE server
# start with cse_server -port <cse_port> on given <cse_host>
# leave empty if script runs locally
CSE_HOST=
CSE_PORT=51001
HWS_HOST=localhost:3121

# remote mashine the FLIB is installed to
# leave empty if script runs locally
# Will be passed to ssh, you can use entries from your ssh config
# and the user@host notation
FLIB_HOST=

# TODO
# implement using digilent jtag tools only
#sudo dpkg -i digilent.adept.runtime_2.16.5-amd64.deb
#sudo dpkg -i digilent.adept.utilities_2.2.1-amd64.deb
#sudo mv /etc/udev/rules.d/52-xilinx-digilent-usb.rules /etc/udev/rules.d/53-xilinx-digilent-usb.rules
#djtgcfg emum
#djtgcfg init -d JtagHs3
#djtgcfg prog -d JtagHs3 -i 0 -f htg.bit


### do not change thing below this line ###

# second parameter is bitfile
BITFILE=$2

if [ $CSE_HOST ]; then
    CSE_SERVER="-server $CSE_HOST:$CSE_PORT"
else
    CSE_SERVER=
fi

if [ $ESN ]; then
	ISE_CABLE="-p usb210 -esn $ESN"
else
	ISE_CABLE="-p auto"
fi

if [ $CABLE_TYPE == "Xilinx" ]; then
    # ESN needs to be lower case
    CABLE=${CABLE_TYPE}/${ESN,,}
    FREQUENCY=6000000
elif [ $CABLE_TYPE == "Digilent" ]; then
    # ESN needs to be upper case
    CABLE=${CABLE_TYPE}/${ESN^^}
    FREQUENCY=15000000
else
    echo "*** Cable type '$CABLE_TYPE' not supportet ***"
    exit -1
fi

# Ask for lacal password at start if needed
if [ ! $FLIB_HOST ]; then
    sudo echo "Superuser access available"
fi

# Reload design from Flash
function reload_fpga {
# from ISE/kintex7/data/xc7k325t_ffg900.bsd
JPROGRAM=001011
"$IMPACT" -batch <<-EOF
setMode -bscan
setCable $ISE_CABLE $CSE_SERVER
Identify -inferir 
identifyMPM 
bsdebug -start 
bsdebug -scanir $JPROGRAM
bsdebug -reset 
quit
EOF
rm _impactbatch.log
sleep 1
echo "Done"
}

# Program FPGA
function program_fpga {
"$IMPACT" -batch <<-EOF
setMode -bscan
setCable $ISE_CABLE $CSE_SERVER
identify
assignfile -p 1 -file "$BITFILE"
program -p 1
quit
EOF
rm _impactbatch.log
sleep 1
echo "Done"
}

# Program Flash
# use 'Erase -p 1 -o -bpionly' to erase Flash 
function program_flash {
"$IMPACT" -batch <<-EOF
setMode -bscan
setCable $ISE_CABLE $CSE_SERVER
Identify -inferir 
identifyMPM 
attachflash -position 1 -bpi "28F512G18F"
assignfiletoattachedflash -position 1 -file "$BITFILE"
Program -p 1 -dataWidth 16 -rs1 NONE -rs0 NONE -bpionly -e -v -loadfpga 
quit
EOF
rm _impactbatch.log
sleep 1
echo "Done"
}

# Reload FPGA configuration from flash
function reload_fpga_vivado {
t=$(tempfile) || exit
trap "rm -f -- '$t'" EXIT
cat > $t <<-EOF
open_hw
connect_hw_server -url $HWS_HOST
current_hw_target [get_hw_targets */xilinx_tcf/${CABLE}]
set_property PARAM.FREQUENCY $FREQUENCY [get_hw_targets */xilinx_tcf/${CABLE}]
open_hw_target
current_hw_device [lindex [get_hw_devices] 0]
boot_hw_device  [lindex [get_hw_devices] 0]
close_hw
EOF
$VIVADO -mode batch -nojournal -nolog -source $t
rm -f -- "$t"
trap - EXIT
rm webtalk.log webtalk.jou
}

# Program FPGA VIVADO
function program_fpga_vivado {
t=$(tempfile) || exit
trap "rm -f -- '$t'" EXIT
cat > $t <<-EOF
open_hw
connect_hw_server -url $HWS_HOST
current_hw_target [get_hw_targets */xilinx_tcf/${CABLE}]
set_property PARAM.FREQUENCY $FREQUENCY [get_hw_targets */xilinx_tcf/${CABLE}]
open_hw_target
set_property PROGRAM.FILE {$BITFILE} [lindex [get_hw_devices] 0]
program_hw_devices [lindex [get_hw_devices] 0]
close_hw
EOF
$VIVADO -mode batch -nojournal -nolog -source $t
rm -f -- "$t"
trap - EXIT
rm webtalk.log webtalk.jou
}

# Program PROM VIVADO
function program_flash_vivado {
t=$(tempfile) || exit
trap "rm -f -- '$t'" EXIT
cat > $t <<-EOF
open_hw
connect_hw_server -url $HWS_HOST
current_hw_target [get_hw_targets */xilinx_tcf/${CABLE}]
set_property PARAM.FREQUENCY $FREQUENCY [get_hw_targets */xilinx_tcf/${CABLE}]
open_hw_target
current_hw_device [lindex [get_hw_devices] 0]
create_hw_cfgmem -hw_device [lindex [get_hw_devices] 0] -mem_dev  [lindex [get_cfgmem_parts {mt28gu01gaax1e-bpi-x16}] 0]
set_property PROGRAM.BLANK_CHECK  0 [ get_property PROGRAM.HW_CFGMEM [lindex [get_hw_devices] 0 ]]
set_property PROGRAM.ERASE  1 [ get_property PROGRAM.HW_CFGMEM [lindex [get_hw_devices] 0 ]]
set_property PROGRAM.CFG_PROGRAM  1 [ get_property PROGRAM.HW_CFGMEM [lindex [get_hw_devices] 0 ]]
set_property PROGRAM.VERIFY  1 [ get_property PROGRAM.HW_CFGMEM [lindex [get_hw_devices] 0 ]]
refresh_hw_device [lindex [get_hw_devices] 0]
set_property PROGRAM.ADDRESS_RANGE  {use_file} [ get_property PROGRAM.HW_CFGMEM [lindex [get_hw_devices] 0 ]]
set_property PROGRAM.FILES [list "$BITFILE" ] [ get_property PROGRAM.HW_CFGMEM [lindex [get_hw_devices] 0]]
set_property PROGRAM.BPI_RS_PINS {none} [ get_property PROGRAM.HW_CFGMEM [lindex [get_hw_devices] 0 ]]
set_property PROGRAM.UNUSED_PIN_TERMINATION {pull-none} [ get_property PROGRAM.HW_CFGMEM [lindex [get_hw_devices] 0 ]]
set_property PROGRAM.BLANK_CHECK  0 [ get_property PROGRAM.HW_CFGMEM [lindex [get_hw_devices] 0 ]]
set_property PROGRAM.ERASE  1 [ get_property PROGRAM.HW_CFGMEM [lindex [get_hw_devices] 0 ]]
set_property PROGRAM.CFG_PROGRAM  1 [ get_property PROGRAM.HW_CFGMEM [lindex [get_hw_devices] 0 ]]
set_property PROGRAM.VERIFY  1 [ get_property PROGRAM.HW_CFGMEM [lindex [get_hw_devices] 0 ]]
startgroup 
if {![string equal [get_property PROGRAM.HW_CFGMEM_TYPE  [lindex [get_hw_devices] 0]] [get_property MEM_TYPE [get_property CFGMEM_PART [get_property PROGRAM.HW_CFGMEM [lindex [get_hw_devices] 0 ]]]]] }  { create_hw_bitstream -hw_device [lindex [get_hw_devices] 0] [get_property PROGRAM.HW_CFGMEM_BITFILE [ lindex [get_hw_devices] 0]]; program_hw_devices [lindex [get_hw_devices] 0]; }; 
program_hw_cfgmem -hw_cfgmem [get_property PROGRAM.HW_CFGMEM [lindex [get_hw_devices] 0 ]]
endgroup
boot_hw_device  [lindex [get_hw_devices] 0]
close_hw
EOF
$VIVADO -mode batch -nojournal -nolog -source $t
rm -f -- "$t"
trap - EXIT
rm webtalk.log webtalk.jou
}

function rescan_pci_base {
if [ "$PCI_DEV" ]; then
    echo "Searching for previous PCI device $PCI_DEV"
else
    echo "Searching for any previous PCI device"
    PCI_DEV=`lspci -d 10dc:beaf -m | cut -d' ' -f1`
    echo "Decives found: $PCI_DEV"
fi
if [ "$PCI_DEV" ]; then
    for i in $PCI_DEV; do
        if [ -f "/sys/bus/pci/devices/0000:$i/remove" ]; then
            echo "Removing previous PCI device $i"
            sudo sh -c "echo 1 > /sys/bus/pci/devices/0000:$i/remove"
        fi
    done
else
    echo "No previous PCI decive found"
fi
sleep 1

echo "Rescanning PCI bus"
sudo sh -c 'echo 1 > /sys/bus/pci/rescan'

echo "Done"
}

function rescan_pci {
if [ $FLIB_HOST ]; then
    echo "Rescanning PCI on $FLIB_HOST."
    echo "Provide password for $FLIB_HOST when prompted."
    ssh -t $FLIB_HOST "$(declare -f rescan_pci_base); PCI_DEV=$PCI_DEV; rescan_pci_base"
else
    rescan_pci_base
fi
}

### MAIN ###

case $1 in
    reload)
        echo -e "Reloading FPGA configuration from Flash and rescanning PCI Bus"
        reload_fpga_vivado
        rescan_pci
        exit
        ;;
    prog)
        echo -e "Programing FPGA and rescanning PCI Bus"
        if [ ! -r "$BITFILE" ]; then
            echo "Bitfile '$BITFILE' not found"
            exit
        fi
        program_fpga_vivado
        rescan_pci
        exit
        ;;
    flash)
        echo -e "Programing onboard Flash"
        if [ ! -r "$BITFILE" ]; then
            echo "Mcsfile '$BITFILE' not found"
            exit
        fi
        program_flash_vivado
        rescan_pci
        exit
        ;;
   rescan)
	echo -e "Rescanning PCI Bus only"
	rescan_pci
	exit
	;;
    *)
        echo -e "usage"
        echo -e "   reload FPGA configuration from Flash:   $0 reload"
        echo -e "   program FPGA:                           $0 prog BITFILE"
        echo -e "   program onboard Flash:                  $0 flash MCSFILE"
        echo -e "   rescan pci bus only:                    $0 resan"
        exit
        ;;
esac



