#!/bin/bash

# Download the latest successfull build form gitlab.
# needs curl and jq
# adopted from https://gitlab.com/morph027/gitlab-ci-helpers/blob/master/get-last-successful-build-artifact.sh

# get private token from:
# https://cbmgsi.githost.io/profile/account
# grab project id with:
# curl -s -H "PRIVATE-TOKEN: $PRIVATE-TOKEN" "${BASEURL}/api/v3/projects" | jq .

set -e

PRIVATE_TOKEN=
BASE_URL=https://cbmgsi.githost.io
PROJECT=2
BUILD_NAME=flib
BUILD_FILE_BASE=htg_k7_flesin
#BUILD_NAME=flim_exdes
#BUILD_FILE_BASE=htg_k7_flib_dpb

# check requirements
REQS=( curl jq )

for REQ in ${REQS[@]}
do
  which ${REQ} >/dev/null
  if [ ! $? -eq 0 ]; then
    echo "requirement ${REQ} is missing"
    exit 1
  fi
done

[ -z $PRIVATE_TOKEN ] && echo "Please add private token" && exit

TMP_FILE=gitlab_build_info.tmp

curl -s -H "PRIVATE-TOKEN: ${PRIVATE_TOKEN}" "${BASE_URL}/api/v3/projects/${PROJECT}/builds" > ${TMP_FILE}

LAST_SUCCESSFUL_BUILD=$(jq -c '.[] | select(.status=="success")  | select(.name=="'${BUILD_NAME}'") | {id}' ${TMP_FILE} | head -n1 | grep -oE '[0-9]+')

BUILD_REF=$(jq -r '.[] | select(.id=='${LAST_SUCCESSFUL_BUILD}') | .commit.short_id' ${TMP_FILE})

BUILD_FILE_NAME=${BUILD_FILE_BASE}_b${LAST_SUCCESSFUL_BUILD}_${BUILD_REF}

download_all() {
    curl -sS -o ${BUILD_NAME}_b${LAST_SUCCESSFUL_BUILD}_${BUILD_REF}.zip -H "PRIVATE-TOKEN: ${PRIVATE_TOKEN}" "${BASE_URL}/api/v3/projects/${PROJECT}/builds/${LAST_SUCCESSFUL_BUILD}/artifacts"
}

download_bit() {
    curl -sS -O -H "PRIVATE-TOKEN: ${PRIVATE_TOKEN}" "${BASE_URL}/fles/flib/builds/${LAST_SUCCESSFUL_BUILD}/artifacts/file/${BUILD_FILE_NAME}.bit"
}

download_mcs() {
    curl -sS -O -H "PRIVATE-TOKEN: ${PRIVATE_TOKEN}" "${BASE_URL}/fles/flib/builds/${LAST_SUCCESSFUL_BUILD}/artifacts/file/${BUILD_FILE_NAME}.mcs"
}

echo "Downloading build '$BUILD_NAME' number '$LAST_SUCCESSFUL_BUILD (${BUILD_REF})'"
set +e

#download_all
download_bit
#download_mcs

rm ${TMP_FILE}
