#!/bin/bash
# Copyright 2014 Jan de Cuveland <cmail@cuveland.de>

set -ex

DIR=/tmp/src

echo "=== Installing dependencies"
sudo aptitude install gcc autoconf automake libtool librdmacm-dev ibverbs-utils rdmacm-utils linux-headers-`uname -r`

echo "=== Downloading sources"
mkdir -p "$DIR"
cd "$DIR"
rm -rf softiwarp
git clone https://github.com/cbm-fles/softiwarp.git
cd "$DIR"/softiwarp
git checkout b453df6dbc395de5133058ce440d5a679b2e2101

echo "=== Building userspace library"
cd "$DIR"/softiwarp/userlib
./autogen.sh
./configure
make

echo "=== Installing userspace library"
sudo make install
sudo ldconfig
sudo mkdir -p /etc/libibverbs.d
sudo ln -sf /usr/local/etc/libibverbs.d/siw.driver /etc/libibverbs.d/

echo "=== Unloading previous kernel module, if any"
sudo modprobe -rv siw

echo "=== Building kernel module"
cd "$DIR/softiwarp/kernel"
patch siw_debug.h <<EOF
diff a/siw_debug.h b/siw_debug.h
--- a/siw_debug.h
+++ b/siw_debug.h
@@ -101,4 +101,4 @@
  */
-#define DPRINT_MASK	0
+#define DPRINT_MASK	(DBG_WR & 0)

 extern void siw_debug_init(void);
EOF
make

echo "=== Installing kernel module"
sudo make install
sudo depmod

echo "=== Loading kernel modules"
for m in rdma_cm ib_uverbs rdma_ucm siw; do
	grep -q "^$m$" /etc/modules || sudo bash -c "echo '$m' >> /etc/modules"
	sudo modprobe "$m"
done

echo "=== Disabling kernel memlock limit"
sudo bash -c 'echo -e "* soft memlock unlimited\n* hard memlock unlimited" > /etc/security/limits.d/10-infiniband.conf'
echo "Re-login for new memlock limit to take effect."

echo "=== Verify install"
ibv_devices
