#!/bin/bash

# Install Docker Engine on a Debian Jessie or Stretch
# from https://docs.docker.com/engine/installation/linux/docker-ce/debian/

echo "*** Uninstall old versions"
sudo apt-get remove docker docker-engine docker.io

set -e

# SET UP THE REPOSITORY
echo "*** Install prerequisites"
sudo apt-get update

# Install packages to allow apt to use a repository over HTTPS
sudo apt-get install \
     apt-transport-https \
     ca-certificates \
     curl \
     gnupg2 \
     software-properties-common

echo "*** Add Docker’s official GPG key"
echo "*** Expected fingerprint: 9DC8 5822 9FC7 DD38 854A E2D8 8D81 803C 0EBF CD88"
curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88

echo "*** Add Stable repository to apt sources"
sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
   $(lsb_release -cs) \
   stable"

echo "*** Install Docker CE"
sudo apt-get update
sudo apt-get install docker-ce

echo "*** Verify install"
sudo docker run hello-world

