#!/bin/bash

set -e
shopt -u nocaseglob
LANG=C

DIR="$(git rev-parse --show-toplevel)"
cd "$DIR"

# PDA library
curl -L https://github.com/cbm-fles/pda/archive/11.4.7.tar.gz | tar xz --transform 's/^pda-[^\/]*/pda_src/'
cd pda_src
./configure --prefix=$DIR/pda
make install
cd ..
