#!/bin/bash

DIR="$( cd "$( dirname "$0" )" && pwd )"

CFG="$DIR/flesnet.cfg"

if [[ "$SLURMD_NODENAME" ]]; then
	# started by slurm
	HOST=$SLURMD_NODENAME

	INLIST=(`grep "^[^#]*input-nodes\s*=" "$CFG" | sed -e 's/.*=\s*//'  -e 's/ib0//' | sed -e ':a;N;$!ba;s/\n/ /g'`)
	CNLIST=(`grep "^[^#]*compute-nodes\s*=" "$CFG" | sed -e 's/.*=\s*//'  -e 's/ib0//' | sed -e ':a;N;$!ba;s/\n/ /g'`)

	for ((i=0; i<${#INLIST[@]}; i++)); do
		if [[ ${INLIST[$i]} = $HOST ]]; then
			"$DIR/flesnet" -i$i &
		fi
	done

	for ((i=0; i<${#CNLIST[@]}; i++)); do
		if [[ ${CNLIST[$i]} = $HOST ]]; then
			"$DIR/flesnet" -c$i &
		fi
	done
	wait
else
	# started directly
	COUNT=`grep -E "^[^#]*(input|compute)-nodes\s*=" "$CFG" | sed -e 's/.*=\s*//'  -e 's/ib0//' | sort -u | wc -l`
	LIST=`grep -E "^[^#]*(input|compute)-nodes\s*=" "$CFG" | sed -e 's/.*=\s*//'  -e 's/ib0//' | sort -u | sed -e ':a;N;$!ba;s/\n/,/g'`

	srun -w "$LIST" -N "$COUNT" -l "$0"
fi
