{
 "title": "CRI Status",
 "tags": [ "FLES" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host Name",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "cri",
    "label": "CRI",
    "query": "SHOW TAG VALUES WITH KEY = \"cri\" WHERE host =~ /^$host$/"
   }
  ]
 },
 "panels": [
  {
   "title": "Host $host",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "host",
   "targets": [
    {}
   ]
  },
  {
   "title": "Data Path Select",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 11, "w": 2, "x": 0, "y": 1 },
   "repeat": "cri",
   "targets": [
    {
     "alias": "Ch. $tag_ch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ch" ], "type": "tag" }
     ],
     "measurement": "ch_status",
     "query": "SELECT last(\"up\") FROM \"ch_status\" WHERE (\"host\" =~ /^$host$/ AND \"cri\" =~ /^$cri$/ AND \"link\" =~ /^[0-3]$/ AND \"link\" = '2') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "data_src" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "cri", "operator": "=~", "value": "/^$cri$/" }
     ]
    }
   ]
  },
  {
   "title": "Ch Status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 11, "w": 2, "x": 2, "y": 1 },
   "repeat": "cri",
   "targets": [
    {
     "alias": "Ch. $tag_ch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ch" ], "type": "tag" }
     ],
     "measurement": "ch_status",
     "query": "SELECT last(\"up\") FROM \"ch_status\" WHERE (\"host\" =~ /^$host$/ AND \"cri\" =~ /^$cri$/ AND \"link\" =~ /^[0-3]$/ AND \"link\" = '2') AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "enable" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "cri", "operator": "=~", "value": "/^$cri$/" }
     ]
    }
   ]
  },
  {
   "title": "CRI $cri at $host: Host PCIe Interface Status",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 4, "y": 1 },
   "repeat": "cri",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dev_status",
     "select": [
      [
       { "params": [ "trans" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Trans" ], "type": "alias" }
      ],
      [
       { "params": [ "stall" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Stall" ], "type": "alias" }
      ],
      [
       { "params": [ "busy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Busy" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "cri", "operator": "=~", "value": "/^$cri$/" }
     ]
    }
   ]
  },
  {
   "title": "CRI $cri at $host: Channel Thoughput",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 8, "y": 1 },
   "repeat": "cri",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Link $tag_ch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ch" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ch_status",
     "query": "SELECT mean(\"throughput\") FROM \"ch_status\" WHERE (\"host\" =~ /^$host$/ AND \"cri\" =~ /^$cri$/ AND \"ch\" =~ /^[0-7]$/) AND $timeFilter GROUP BY time($__interval), \"ch\" fill(null)",
     "select": [
      [
       { "params": [ "throughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "cri", "operator": "=~", "value": "/^$cri$/" },
      { "condition": "AND", "key": "ch", "operator": "=~", "value": "/^[0-7]$/" }
     ]
    }
   ]
  },
  {
   "title": "CRI $cri at $host: Microslice Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 14, "y": 1 },
   "repeat": "cri",
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "alias": "Link $tag_ch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ch" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ch_status",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "cri", "operator": "=~", "value": "/^$cri$/" },
      { "condition": "AND", "key": "ch", "operator": "=~", "value": "/^[0-7]$/" }
     ]
    }
   ]
  },
  {
   "title": "CRI $cri at $host: Link Backpressure",
   "type": "graph",
   "gridPos": { "h": 11, "w": 4, "x": 20, "y": 1 },
   "repeat": "cri",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Link $tag_ch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ch" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ch_status",
     "select": [
      [
       { "params": [ "mc_stall" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "cri", "operator": "=~", "value": "/^$cri$/" },
      { "condition": "AND", "key": "ch", "operator": "=~", "value": "/^[0-7]$/" }
     ]
    }
   ]
  }
 ]
}