{
 "title": "FLESNET Overview",
 "tags": [ "FLES" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "input_index",
    "label": "Input Index",
    "query": "SHOW TAG VALUES WITH KEY = \"input_index\""
   },
   {
    "name": "output_index",
    "label": "Output Index",
    "query": "SHOW TAG VALUES WITH KEY = \"output_index\""
   }
  ]
 },
 "panels": [
  { "title": "Total rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Data Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "send_buffer_status",
     "select": [
      [
       { "params": [ "data_rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*1000/$__interval_ms" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Rate per Subsystem",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_sys_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_id" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "send_buffer_status",
     "select": [
      [
       { "params": [ "data_rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*1000/$__interval_ms" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "send_buffer_status",
     "select": [
      [
       { "params": [ "data_rate" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "*1000/$__interval_ms" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Microslice rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_cri $tag_ch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "cri" ], "type": "tag" },
      { "params": [ "ch" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ch_status",
     "select": [
      [
       { "params": [ "rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Rates per Input Channel",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_sys_id $tag_eq_id",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sys_id" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "eq_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "send_buffer_status",
     "select": [
      [
       { "params": [ "data_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "ELOG", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  { "title": "Timeslice Analyzer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Timeslices",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "alias": "$tag_output_prefix ($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "output_prefix" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timeslice_analyzer_status",
     "select": [
      [
       { "params": [ "timeslice_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "$tag_output_prefix ($tag_host) errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "output_prefix" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timeslice_analyzer_status",
     "select": [
      [
       { "params": [ "timeslice_error_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Timeslice Components",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "alias": "$tag_output_prefix ($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "output_prefix" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timeslice_analyzer_status",
     "select": [
      [
       { "params": [ "component_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "$tag_output_prefix ($tag_host) errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "output_prefix" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timeslice_analyzer_status",
     "select": [
      [
       { "params": [ "component_error_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Microslices",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "alias": "$tag_output_prefix ($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "output_prefix" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timeslice_analyzer_status",
     "select": [
      [
       { "params": [ "microslice_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "$tag_output_prefix ($tag_host) errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "output_prefix" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timeslice_analyzer_status",
     "select": [
      [
       { "params": [ "microslice_error_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data content",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_output_prefix ($tag_host)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "output_prefix" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timeslice_analyzer_status",
     "select": [
      [
       { "params": [ "content_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Data rates per channel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Data Rates per Output Channel",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host ($tag_output_index)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "output_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "timeslice_buffer_status",
     "select": [
      [
       { "params": [ "data_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Flesnet sender (en) buffer state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "Send Data Buffer Status for Channel $input_index",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
     "repeat": "input_index",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "send_buffer_status",
       "select": [
        [
         { "params": [ "data_used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "input_index", "operator": "=~", "value": "/^$input_index$/" }
       ]
      },
      {
       "alias": "sending",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "send_buffer_status",
       "select": [
        [
         { "params": [ "data_sending" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "input_index", "operator": "=~", "value": "/^$input_index$/" }
       ]
      },
      {
       "alias": "freeing",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "send_buffer_status",
       "select": [
        [
         { "params": [ "data_freeing" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "input_index", "operator": "=~", "value": "/^$input_index$/" }
       ]
      },
      {
       "alias": "free",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "send_buffer_status",
       "select": [
        [
         { "params": [ "data_free" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "input_index", "operator": "=~", "value": "/^$input_index$/" }
       ]
      }
     ]
    },
    {
     "title": "Send Descriptor Buffer Status for Channel $input_index",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
     "repeat": "input_index",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "send_buffer_status",
       "select": [
        [
         { "params": [ "desc_used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "input_index", "operator": "=~", "value": "/^$input_index$/" }
       ]
      },
      {
       "alias": "sending",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "send_buffer_status",
       "select": [
        [
         { "params": [ "desc_sending" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "input_index", "operator": "=~", "value": "/^$input_index$/" }
       ]
      },
      {
       "alias": "freeing",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "send_buffer_status",
       "select": [
        [
         { "params": [ "desc_freeing" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "input_index", "operator": "=~", "value": "/^$input_index$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Flesnet receiver (pn) buffer state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 }
  },
  {
   "title": "Receive Data Buffer Status for Output Index $output_index and Input Index $input_index",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "repeat": "output_index",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "used $tag_input_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "input_index" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "recv_buffer_status",
     "select": [
      [
       { "params": [ "data_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "output_index", "operator": "=~", "value": "/^$output_index$/" }
     ]
    },
    {
     "alias": "pending release $tag_input_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "input_index" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "recv_buffer_status",
     "select": [
      [
       { "params": [ "data_freeing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "output_index", "operator": "=~", "value": "/^$output_index$/" }
     ]
    }
   ]
  },
  {
   "title": "Receive Descriptor Buffer Status for Output Index $output_index and Input Index $input_index",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "repeat": "output_index",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "recv_buffer_status",
     "select": [
      [
       { "params": [ "desc_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "output_index", "operator": "=~", "value": "/^$output_index$/" },
      { "condition": "AND", "key": "input_index", "operator": "=~", "value": "/^$input_index$/" }
     ]
    },
    {
     "alias": "freeing",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "recv_buffer_status",
     "select": [
      [
       { "params": [ "desc_freeing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "output_index", "operator": "=~", "value": "/^$output_index$/" },
      { "condition": "AND", "key": "input_index", "operator": "=~", "value": "/^$input_index$/" }
     ]
    }
   ]
  },
  {
   "title": "Aggregate Receive Data Buffer Status for Output Index $output_index",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "repeat": "output_index",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timeslice_buffer_status",
     "select": [
      [
       { "params": [ "data_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "output_index", "operator": "=~", "value": "/^$output_index$/" }
     ]
    },
    {
     "alias": "mixed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timeslice_buffer_status",
     "select": [
      [
       { "params": [ "data_mixed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "output_index", "operator": "=~", "value": "/^$output_index$/" }
     ]
    },
    {
     "alias": "pending release",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timeslice_buffer_status",
     "select": [
      [
       { "params": [ "data_freeing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "output_index", "operator": "=~", "value": "/^$output_index$/" }
     ]
    }
   ]
  },
  {
   "title": "Aggregate Receive Descriptor Buffer Status for Output Index $output_index",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "repeat": "output_index",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "used",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timeslice_buffer_status",
     "select": [
      [
       { "params": [ "desc_used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "output_index", "operator": "=~", "value": "/^$output_index$/" }
     ]
    },
    {
     "alias": "mixed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timeslice_buffer_status",
     "select": [
      [
       { "params": [ "desc_mixed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "output_index", "operator": "=~", "value": "/^$output_index$/" }
     ]
    },
    {
     "alias": "pending release",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "timeslice_buffer_status",
     "select": [
      [
       { "params": [ "desc_freeing" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "output_index", "operator": "=~", "value": "/^$output_index$/" }
     ]
    }
   ]
  },
  {
   "title": "Runs",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Rates per Input Channel",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host $tag_sys_id $tag_eq_id ($tag_input_index)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "input_index" ], "type": "tag" },
      { "params": [ "sys_id" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "eq_id" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "send_buffer_status",
     "select": [
      [
       { "params": [ "data_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}