#!/bin/bash
echo "Searching for previous PCI device"
NODE=`lspci -d 10dc:beaf -m | cut -d' ' -f1`
if [ "$NODE" ]; then
        echo "Found previous PCI decive at $NODE"
        if [ -f "/sys/bus/pci/devices/0000:$NODE/remove" ]; then
                echo "Removing previous PCI device"
                sudo sh -c "echo 1 > /sys/bus/pci/devices/0000:$NODE/remove"
        fi
else
        echo "No previous PCI decive found"
fi
sleep 1

echo "Rescanning PCI bus"
sudo sh -c 'echo 1 > /sys/bus/pci/rescan'
