{
 "title": "01_Global_Status",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Dashboard List", "type": "dashlist", "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 } },
  { "title": "Error on Occurance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Error / Overflow table on Occurance",
   "type": "table",
   "description": "Shows table with detailed information on occurance of an error or overflow\n\"No data to show\" indicates everything is healthy.",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 5 },
   "targets": [
    {
     "measurement": "flib_data",
     "query": "SELECT \"host\",\"flib\",\"he\",\"se\",\"eo\",\"do\" FROM \"flib_data\" WHERE (\"data_sel\" != '\"disable\"' AND \"he\" = true OR \"se\" = true OR \"eo\" = true OR \"do\" = true) AND $timeFilter",
     "select": [
      [
       { "params": [ "he" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      }
     ]
    }
   ]
  },
  {
   "title": "Data Select \"Link\" & Link Down",
   "type": "table",
   "description": "Shows table with detailed information on occurance of an Data Select as \"link\" but Link Up is \"Down\".\n\"No data to show\" indicates everything is healthy.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"host\",\"flib\",\"up\" FROM \"flib_data\" WHERE (\"data_sel\" = '\"link\"' AND \"up\" = false) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "PCI Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "PCI transmit mean",
   "type": "graph",
   "description": "trans:\ndata is transmitted via PCIe interface (ratio)\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "PCIe_Trans",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "pci_trans" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PCI transmit mean",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "pci_trans" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PCI idle mean",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "pci_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PCI stall mean",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "pci_stall" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PCI idle mean",
   "type": "graph",
   "description": "total PCIe idle mean\n\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "PCIe_Idle",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "pci_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "PCI stall mean",
   "type": "graph",
   "description": "stall: \nback pressure on PCIe interface from host (ratio)\n\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "PCIe_Stall",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "pci_stall" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "fifo fill", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "fifo fill",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "repeat": "get_flibs",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "fill 1",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "fill0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "fill 2",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "fill1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "fill 3",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "fill2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "fill 4",
     "groupBy": [
      { "params": [ "5s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "fill3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "fill 5",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "fill4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "fill 6",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "fill5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "fill 7",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "fill6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "fill 8",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "fill7" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Average Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Average dma stall",
   "type": "graph",
   "description": "Average dma_s value on the Flibs",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "Avg. dma_s",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "dma_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      }
     ]
    }
   ]
  },
  {
   "title": "Average data stall",
   "type": "graph",
   "description": "Average data_stall value on the Flibs",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "Avg. data_stall",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "data_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      }
     ]
    }
   ]
  },
  {
   "title": "Average desc stall",
   "type": "graph",
   "description": "Average desc_stall value on the Flibs",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "Avg. desc_stall",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "desc_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      }
     ]
    }
   ]
  },
  {
   "title": "Average backpreassure",
   "type": "graph",
   "description": "Average din_full value on the Flibs",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "Avg. din_full",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "din_full" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      }
     ]
    }
   ]
  },
  {
   "title": "Average data fifo max words",
   "type": "graph",
   "description": "Average d_max value on the Flibs",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "Integer" }
   ],
   "targets": [
    {
     "alias": "Avg. d_max",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "d_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      }
     ]
    }
   ]
  },
  {
   "title": "Average Microslice rate",
   "type": "graph",
   "description": "Average event rate value on the Flibs",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "Avg. event rate",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "event_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      }
     ]
    }
   ]
  }
 ]
}