{
 "title": "02_Host_Status",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "get_hosts",
    "label": "Host",
    "query": "SHOW TAG VALUES WITH KEY=\"host\""
   },
   {
    "name": "get_flibs",
    "label": "Flibs",
    "query": "SHOW TAG VALUES WITH KEY=\"flib\" WHERE host =~ /$get_hosts/"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard List", "type": "dashlist", "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 } },
  { "title": "Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "hard error on host",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 5 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "measurement": "flib_data",
     "query": "SELECT \"he\" FROM \"flib_data\" WHERE (\"data_sel\" != '\"disable\"' AND \"host\" =~ /^$get_hosts$/ AND \"flib\" =~ /^$get_flibs$/ AND \"he\" = true) AND $timeFilter",
     "select": [
      [
       { "params": [ "he" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" }
     ]
    }
   ]
  },
  {
   "title": "soft error on host",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 5 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "measurement": "flib_data",
     "query": "SELECT \"se\" FROM \"flib_data\" WHERE (\"data_sel\" != '\"disable\"' AND \"host\" =~ /^$get_hosts$/ AND \"flib\" =~ /^$get_flibs$/ AND \"se\" = true) AND $timeFilter",
     "select": [
      [
       { "params": [ "he" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" }
     ]
    }
   ]
  },
  {
   "title": "eoe fifo overflow on host",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 5 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "measurement": "flib_data",
     "query": "SELECT \"eo\" FROM \"flib_data\" WHERE (\"data_sel\" != '\"disable\"' AND \"host\" =~ /^$get_hosts$/ AND \"flib\" =~ /^$get_flibs$/ AND \"eo\" = true) AND $timeFilter",
     "select": [
      [
       { "params": [ "he" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" }
     ]
    }
   ]
  },
  {
   "title": "data fifo overflow on host",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 5 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "measurement": "flib_data",
     "query": "SELECT \"do\" FROM \"flib_data\" WHERE (\"data_sel\" != '\"disable\"' AND \"host\" =~ /^$get_hosts$/ AND \"flib\" =~ /^$get_flibs$/ AND \"do\" = true) AND $timeFilter",
     "select": [
      [
       { "params": [ "he" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" }
     ]
    }
   ]
  },
  {
   "title": "Data Select \"Link\" & Link Down",
   "type": "table",
   "description": "Table of links with data select as \"link\" and link up as \"down\", given as an error condition.\nShows table on occurance",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"flib\",\"link\",\"data_sel\",\"up\" FROM \"flib_data\" WHERE (\"flib\" =~ /^$get_flibs$/ AND \"host\" =~ /^$get_hosts$/ AND \"data_sel\" = '\"link\"' AND \"up\" = false) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "PCI Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "PCI Transmit",
   "type": "graph",
   "description": "idle: \nPCIe interface is idle (ratio)\nstall: \nback pressure on PCIe interface from host (ratio)\ntrans:\ndata is transmitted via PCIe interface (ratio)\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "PCIe_Trans",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "pci_trans" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "PCI transmit current",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "pci_trans" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "PCI idle gauge current",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "pci_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "PCI stall current",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "pci_stall" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "PCI Idle",
   "type": "graph",
   "description": "idle: \nPCIe interface is idle (ratio)\nstall: \nback pressure on PCIe interface from host (ratio)\ntrans:\ndata is transmitted via PCIe interface (ratio)\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "PCIe_Idle",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "pci_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "PCI Stall",
   "type": "graph",
   "description": "idle: \nPCIe interface is idle (ratio)\nstall: \nback pressure on PCIe interface from host (ratio)\ntrans:\ndata is transmitted via PCIe interface (ratio)\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "PCIe_Stall",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "pci_stall" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  { "title": "fifo fill", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "fifo fill",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "repeat": "get_flibs",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "fill 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "fill0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "fill 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "fill1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "fill 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "fill2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "fill 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "fill3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "fill 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "fill4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "fill 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "fill5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "fill 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "fill6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "fill 8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "fill7" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  { "title": "Error Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Error Table (Host/Flibs)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "measurement": "flib_data",
     "query": "SELECT \"flib\",\"link\",\"he\", \"se\", \"eo\", \"do\" FROM \"flib_data\" WHERE (\"flib\" =~ /^$get_flibs$/ AND \"host\" =~ /^$get_hosts$/ AND \"data_sel\" != '\"disable\"' AND \"he\" = true OR \"se\" = true OR \"eo\" = true OR \"do\" = true) AND $timeFilter",
     "select": [
      [
       { "params": [ "he" ], "type": "field" }
      ],
      [
       { "params": [ "se" ], "type": "field" }
      ],
      [
       { "params": [ "eo" ], "type": "field" }
      ],
      [
       { "params": [ "do" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" },
      {
       "condition": "AND",
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      }
     ]
    }
   ]
  },
  { "title": "Average Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Average dma stall",
   "type": "graph",
   "description": "Average dma_s value on the Flibs",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "Avg. dma_s",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "dma_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Average data stall",
   "type": "graph",
   "description": "Average data_stall value on the Flibs",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "Avg. data_stall",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "data_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Average desc stall",
   "type": "graph",
   "description": "Average desc_stall value on the Flibs",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "Avg. desc_stall",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "desc_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Average backpreassure",
   "type": "graph",
   "description": "Average din_full value on the Flibs",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "Avg. din_full",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "din_full" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Average data fifo max words",
   "type": "graph",
   "description": "Average d_max value on the Flibs",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "Integer" }
   ],
   "targets": [
    {
     "alias": "Avg. d_max",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "d_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Microslice rate",
   "type": "graph",
   "description": "Average event rate value on the Flibs",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 72 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "Avg. event rate",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "event_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  { "title": "Active Link Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Currently active Links",
   "type": "table",
   "description": "Number of currently active Links on the Flib",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 82 },
   "targets": [
    {
     "alias": "Number of active Links",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "query": "SELECT \"flib\",max(\"active_links\") FROM \"flib_data\" WHERE (\"host\" =~ /^$get_hosts$/ AND \"flib\" =~ /^$get_flibs$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "active_links" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$get_hosts$/" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" }
     ]
    }
   ]
  }
 ]
}