{
 "title": "03_Flib_Status",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "get_hosts",
    "label": "Host",
    "query": "SELECT \"host\",\"up\" FROM \"flib_data\""
   },
   {
    "name": "var_flib",
    "label": "FLIB",
    "query": "SELECT \"flib\",\"up\" FROM flib_data"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard List", "type": "dashlist", "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 } },
  { "title": "Error", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "hard error",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 5 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "measurement": "flib_data",
     "query": "SELECT \"he\" FROM \"flib_data\" WHERE (\"data_sel\" != '\"disable\"' AND \"flib\" =~ /^$var_flib$/ AND \"host\" =~ /^$get_hosts$/ AND \"he\" = true) AND $timeFilter",
     "select": [
      [
       { "params": [ "he" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "soft error",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 5 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "measurement": "flib_data",
     "query": "SELECT \"se\" FROM \"flib_data\" WHERE (\"data_sel\" != '\"disable\"' AND \"flib\" =~ /^$var_flib$/ AND \"host\" =~ /^$get_hosts$/ AND \"se\" = true) AND $timeFilter",
     "select": [
      [
       { "params": [ "se" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "eoe fifo overflow",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 5 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "measurement": "flib_data",
     "query": "SELECT \"he\" FROM \"flib_data\" WHERE (\"data_sel\" != '\"disable\"' AND \"flib\" =~ /^$var_flib$/ AND \"host\" =~ /^$get_hosts$/ AND \"eo\" = true) AND $timeFilter",
     "select": [
      [
       { "params": [ "he" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "data fifo overflow",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 5 },
   "format": "dateTimeAsIso",
   "valueName": "last_time",
   "targets": [
    {
     "measurement": "flib_data",
     "query": "SELECT \"he\" FROM \"flib_data\" WHERE (\"data_sel\" != '\"disable\"' AND \"flib\" =~ /^$var_flib$/ AND \"host\" =~ /^$get_hosts$/ AND \"do\" = true) AND $timeFilter",
     "select": [
      [
       { "params": [ "he" ], "type": "field" }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Data Select \"Link\" & Link Down",
   "type": "table",
   "description": "Table of links with data select as \"link\" and link up as \"down\", given as an error condition.\nShows table on occurance",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"link\",\"data_sel\",\"up\" FROM \"flib_data\" WHERE (\"data_sel\" = '\"link\"' AND \"up\" = false AND \"flib\" =~ /^$var_flib$/ AND \"host\" =~ /^$get_hosts$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "PCI Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "PCI Transmit",
   "type": "graph",
   "description": "idle: \nPCIe interface is idle (ratio)\nstall: \nback pressure on PCIe interface from host (ratio)\ntrans:\ndata is transmitted via PCIe interface (ratio)\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "PCIe_Trans",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "pci_trans" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "PCI transmit current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "pci_trans" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "PCI idle current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "pci_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "PCI stall current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "pci_stall" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "PCI Idle",
   "type": "graph",
   "description": "idle: \nPCIe interface is idle (ratio)\nstall: \nback pressure on PCIe interface from host (ratio)\ntrans:\ndata is transmitted via PCIe interface (ratio)\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "PCIe_Idle",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "pci_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "PCI Stall",
   "type": "graph",
   "description": "idle: \nPCIe interface is idle (ratio)\nstall: \nback pressure on PCIe interface from host (ratio)\ntrans:\ndata is transmitted via PCIe interface (ratio)\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "PCIe_Stall",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "pci_stall" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  { "title": "FLIB Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "data stall",
   "type": "graph",
   "description": "stall from full data buffer (ratio)",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "link 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "data_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "0" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "data_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "data_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "data_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "data_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "data_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "5" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "data_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "6" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "data_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "7" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "dma stall",
   "type": "graph",
   "description": "stall from dma mux (ratio)",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "link 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "dma_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "0" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "dma_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "dma_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "dma_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "dma_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "dma_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "5" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "dma_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "6" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "dma_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "7" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "desc stall",
   "type": "graph",
   "description": "stall from full desc buffer (ratio)",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "link 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "desc_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "0" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "desc_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "desc_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "desc_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "desc_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "desc_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "5" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "desc_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "6" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "desc_s" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "7" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Microslice rate",
   "type": "graph",
   "description": "ms processing rate (Hz*)",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "event_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "0" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "event_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "event_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "event_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "event_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "event_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "5" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "event_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "6" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "event_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "7" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "data fifo max words",
   "type": "graph",
   "description": "maximum number of words in d_fifo",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Integer" }
   ],
   "targets": [
    {
     "alias": "link 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "query": "SELECT mean(\"up\") FROM \"flib_data\" WHERE (\"data_sel\" = 'pgen' AND \"link\" = '0' AND \"flib\" =~ /^$var_flib$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "d_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "0" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" }
     ]
    },
    {
     "alias": "link 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "d_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "d_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "d_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "d_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "d_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "5" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "d_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "6" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "d_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "7" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "backpreassure",
   "type": "graph",
   "description": "back pressure to link (ratio)",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 41 },
   "yaxes": [
    { "format": "short", "label": "Float, ratio %" }
   ],
   "targets": [
    {
     "alias": "link 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "din_full" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "0" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "din_full" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "1" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "din_full" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "2" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "din_full" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "3" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "din_full" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "4" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "din_full" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "5" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "din_full" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "6" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    },
    {
     "alias": "link 7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "flib_data",
     "select": [
      [
       { "params": [ "din_full" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      },
      { "condition": "AND", "key": "link", "operator": "=", "value": "7" },
      { "condition": "AND", "key": "flib", "operator": "=~", "value": "/^$var_flib$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" }
     ]
    }
   ]
  },
  { "title": "Error Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Error Table (Host/Flibs)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "measurement": "flib_data",
     "query": "SELECT \"link\",\"data_sel\",\"up\",\"he\",\"se\",\"eo\",\"do\" FROM \"flib_data\" WHERE (\"data_sel\" != '\"disable\"' AND \"link\" = '7' AND \"flib\" =~ /^$var_flib$/ AND \"host\" =~ /^$get_hosts$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "he" ], "type": "field" }
      ],
      [
       { "params": [ "se" ], "type": "field" }
      ],
      [
       { "params": [ "eo" ], "type": "field" }
      ],
      [
       { "params": [ "do" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" },
      {
       "condition": "AND",
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      }
     ]
    },
    {
     "measurement": "flib_data",
     "query": "SELECT \"link\",\"data_sel\",\"up\",\"he\",\"se\",\"eo\",\"do\" FROM \"flib_data\" WHERE (\"data_sel\" != '\"disable\"' AND \"link\" = '6' AND \"flib\" =~ /^$var_flib$/ AND \"host\" =~ /^$get_hosts$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "he" ], "type": "field" }
      ],
      [
       { "params": [ "se" ], "type": "field" }
      ],
      [
       { "params": [ "eo" ], "type": "field" }
      ],
      [
       { "params": [ "do" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" },
      {
       "condition": "AND",
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      }
     ]
    },
    {
     "measurement": "flib_data",
     "query": "SELECT \"link\",\"data_sel\",\"up\",\"he\",\"se\",\"eo\",\"do\" FROM \"flib_data\" WHERE (\"data_sel\" != '\"disable\"' AND \"link\" = '5' AND \"flib\" =~ /^$var_flib$/ AND \"host\" =~ /^$get_hosts$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "he" ], "type": "field" }
      ],
      [
       { "params": [ "se" ], "type": "field" }
      ],
      [
       { "params": [ "eo" ], "type": "field" }
      ],
      [
       { "params": [ "do" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" },
      {
       "condition": "AND",
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      }
     ]
    },
    {
     "measurement": "flib_data",
     "query": "SELECT \"link\",\"data_sel\",\"up\",\"he\",\"se\",\"eo\",\"do\" FROM \"flib_data\" WHERE (\"data_sel\" != '\"disable\"' AND \"link\" = '4' AND \"flib\" =~ /^$var_flib$/ AND \"host\" =~ /^$get_hosts$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "he" ], "type": "field" }
      ],
      [
       { "params": [ "se" ], "type": "field" }
      ],
      [
       { "params": [ "eo" ], "type": "field" }
      ],
      [
       { "params": [ "do" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" },
      {
       "condition": "AND",
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      }
     ]
    },
    {
     "measurement": "flib_data",
     "query": "SELECT \"link\",\"data_sel\",\"up\",\"he\",\"se\",\"eo\",\"do\" FROM \"flib_data\" WHERE (\"data_sel\" != '\"disable\"' AND \"link\" = '3' AND \"flib\" =~ /^$var_flib$/ AND \"host\" =~ /^$get_hosts$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "he" ], "type": "field" }
      ],
      [
       { "params": [ "se" ], "type": "field" }
      ],
      [
       { "params": [ "eo" ], "type": "field" }
      ],
      [
       { "params": [ "do" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" },
      {
       "condition": "AND",
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      }
     ]
    },
    {
     "measurement": "flib_data",
     "query": "SELECT \"link\",\"data_sel\",\"up\",\"he\",\"se\",\"eo\",\"do\" FROM \"flib_data\" WHERE (\"data_sel\" != '\"disable\"' AND \"link\" = '2' AND \"flib\" =~ /^$var_flib$/ AND \"host\" =~ /^$get_hosts$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "he" ], "type": "field" }
      ],
      [
       { "params": [ "se" ], "type": "field" }
      ],
      [
       { "params": [ "eo" ], "type": "field" }
      ],
      [
       { "params": [ "do" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" },
      {
       "condition": "AND",
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      }
     ]
    },
    {
     "measurement": "flib_data",
     "query": "SELECT \"link\",\"data_sel\",\"up\",\"he\",\"se\",\"eo\",\"do\" FROM \"flib_data\" WHERE (\"data_sel\" != '\"disable\"' AND \"link\" = '1' AND \"flib\" =~ /^$var_flib$/ AND \"host\" =~ /^$get_hosts$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "he" ], "type": "field" }
      ],
      [
       { "params": [ "se" ], "type": "field" }
      ],
      [
       { "params": [ "eo" ], "type": "field" }
      ],
      [
       { "params": [ "do" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "flib", "operator": "=~", "value": "/^$get_flibs$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$get_hosts$/" },
      {
       "condition": "AND",
       "key": "data_sel",
       "operator": "=",
       "value": "\"pgen\""
      }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"link\",\"data_sel\",\"up\",\"he\",\"se\",\"eo\",\"do\" FROM \"flib_data\" WHERE (\"data_sel\" != '\"disable\"' AND \"link\" = '0' AND \"flib\" =~ /^$var_flib$/ AND \"host\" =~ /^$get_hosts$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}