// build/cri_registers.hpp: CRI Register Definitions
//
// Note:
// This file was automatically generated from:
// ../flim/src/packages/fles_registers.vhd
// Repository is: git repository
// Repository Revision: 567e0eb5fbc15de24dbf4dd7cb895150b7656909
// Repository Status: clean
// Build Timestamp: Fri Jul  2 13:58:28 CEST 2021
// Build System: hutter@eda02
#define CRI_C_BUILD_REPO 1
#define CRI_C_BUILD_DATE 1625227108
#define CRI_C_BUILD_REVISION 567e0eb5fbc15de24dbf4dd7cb895150b7656909
#define CRI_C_BUILD_STATUS_CLEAN 1
#define CRI_C_BUILD_HOST 65646130320000000000000000000000
#define CRI_C_BUILD_USER 68757474657200000000000000000000
#define CRI_C_HARDWARE_ID 0xf1e5
#define CRI_C_TIMEOUT_PATTERN 0xa5a5a5a5
#define CRI_C_ILL_ADDR_PATTERN 0xa6a6a6a6
#define CRI_C_HARDWARE_VERSION 2
#define CRI_C_CH_ADDR_SEL 15
#define CRI_C_DMA_ADDR_SEL 14
#define CRI_REG_HARDWARE_INFO 0
#define CRI_REG_BUILD_FLAGS 1
#define CRI_REG_BUILD_REV_0 2
#define CRI_REG_BUILD_REV_1 3
#define CRI_REG_BUILD_REV_2 4
#define CRI_REG_BUILD_REV_3 5
#define CRI_REG_BUILD_REV_4 6
#define CRI_REG_BUILD_DATE_L 7
#define CRI_REG_BUILD_DATE_H 8
#define CRI_REG_BUILD_HOST_0 9
#define CRI_REG_BUILD_HOST_1 10
#define CRI_REG_BUILD_HOST_2 11
#define CRI_REG_BUILD_HOST_3 12
#define CRI_REG_BUILD_USER_0 13
#define CRI_REG_BUILD_USER_1 14
#define CRI_REG_BUILD_USER_2 15
#define CRI_REG_BUILD_USER_3 16
#define CRI_REG_N_CHANNELS 17
#define CRI_REG_TESTREG_DEVICE 18
#define CRI_REG_TEST_TIMEOUT 19
#define CRI_REG_FLIM_CFG 20
#define CRI_REG_FLIM_STS 21
#define CRI_REG_MC_CNT_CFG_L 22
#define CRI_REG_MC_CNT_CFG_H 23
#define CRI_REG_PCI_PERF_CFG 24
#define CRI_REG_PCI_PERF_CYCLE 25
#define CRI_REG_PCI_PERF_DMA_TRANS 26
#define CRI_REG_PCI_PERF_DMA_STALL 27
#define CRI_REG_PCI_PERF_DMA_BUSY 28
#define CRI_REG_PCI_PERF_DMA_MAX_NRDY 29
#define CRI_REG_EBDM_N_SG_CONFIG 0
#define CRI_REG_EBDM_BUFFER_SIZE_L 1
#define CRI_REG_EBDM_BUFFER_SIZE_H 2
#define CRI_REG_RBDM_N_SG_CONFIG 3
#define CRI_REG_RBDM_BUFFER_SIZE_L 4
#define CRI_REG_RBDM_BUFFER_SIZE_H 5
#define CRI_REG_EBDM_SW_READ_POINTER_L 6
#define CRI_REG_EBDM_SW_READ_POINTER_H 7
#define CRI_REG_RBDM_SW_READ_POINTER_L 8
#define CRI_REG_RBDM_SW_READ_POINTER_H 9
#define CRI_REG_DMA_CTRL 10
#define CRI_REG_EBDM_FPGA_WRITE_POINTER_L 11
#define CRI_REG_EBDM_FPGA_WRITE_POINTER_H 12
#define CRI_REG_RBDM_FPGA_WRITE_POINTER_L 13
#define CRI_REG_RBDM_FPGA_WRITE_POINTER_H 14
#define CRI_REG_TESTREG_DMA 15
#define CRI_REG_SGENTRY_ADDR_LOW 16
#define CRI_REG_SGENTRY_ADDR_HIGH 17
#define CRI_REG_SGENTRY_LEN 18
#define CRI_REG_SGENTRY_CTRL 19
#define CRI_REG_MISC_CFG 20
#define CRI_REG_MISC_STS 21
#define CRI_REG_EBDM_OFFSET_L 22
#define CRI_REG_EBDM_OFFSET_H 23
#define CRI_REG_DESC_CNT_L 24
#define CRI_REG_DESC_CNT_H 25
#define CRI_REG_PKT_PERF_CFG 26
#define CRI_REG_PKT_PERF_CYCLE 27
#define CRI_REG_PKT_PERF_DMA_TRANS 28
#define CRI_REG_PKT_PERF_DMA_STALL 29
#define CRI_REG_PKT_PERF_DMA_BUSY 30
#define CRI_REG_PKT_PERF_EBUF_STALL 31
#define CRI_REG_PKT_PERF_RBUF_STALL 32
#define CRI_REG_PKT_PERF_N_EVENTS 33
#define CRI_REG_PKT_MC_TIME_L 34
#define CRI_REG_PKT_MC_TIME_H 35
#define CRI_REG_TESTREG_DATA 0
#define CRI_REG_GTX_DATAPATH_CFG 1
#define CRI_REG_GTX_MC_PGEN_CFG_L 2
#define CRI_REG_GTX_MC_PGEN_CFG_H 3
#define CRI_REG_GTX_MC_PGEN_MC_PENDING 4
#define CRI_REG_GTX_PERF_CFG 5
#define CRI_REG_GTX_PERF_CYCLE 6
#define CRI_REG_GTX_PERF_MC_TRANS 7
#define CRI_REG_GTX_PERF_MC_STALL 8
#define CRI_REG_GTX_PERF_MC_BUSY 9
