// build/cri_registers.hpp: CRI Register Definitions
//
// Note:
// This file was automatically generated from:
// ../flim/src/packages/fles_registers.vhd
// Repository is: git repository
// Repository Revision: e336d4c2304c48baf202e9135a809afdce36c846
// Repository Status: dirty
// Build Timestamp: Tue May 11 16:54:01 CEST 2021
// Build System: hutter@eda02
#define CRI_C_BUILD_REPO 1
#define CRI_C_BUILD_DATE 1620744841
#define CRI_C_BUILD_REVISION e336d4c2304c48baf202e9135a809afdce36c846
#define CRI_C_BUILD_STATUS_CLEAN 0
#define CRI_C_BUILD_HOST 65646130320000000000000000000000
#define CRI_C_BUILD_USER 68757474657200000000000000000000
#define CRI_C_HARDWARE_ID 0x4844
#define CRI_C_TIMEOUT_PATTERN 0xa5a5a5a5
#define CRI_C_ILL_ADDR_PATTERN 0xa6a6a6a6
#define CRI_C_HARDWARE_VERSION 1
#define CRI_C_CH_ADDR_SEL 15
#define CRI_C_DMA_ADDR_SEL 14
#define CRI_REG_HARDWARE_INFO 0
#define CRI_REG_BUILD_FLAGS 1
#define CRI_REG_BUILD_REV_0 2
#define CRI_REG_BUILD_REV_1 3
#define CRI_REG_BUILD_REV_2 4
#define CRI_REG_BUILD_REV_3 5
#define CRI_REG_BUILD_REV_4 6
#define CRI_REG_BUILD_DATE_L 7
#define CRI_REG_BUILD_DATE_H 8
#define CRI_REG_BUILD_HOST_0 9
#define CRI_REG_BUILD_HOST_1 10
#define CRI_REG_BUILD_HOST_2 11
#define CRI_REG_BUILD_HOST_3 12
#define CRI_REG_BUILD_USER_0 13
#define CRI_REG_BUILD_USER_1 14
#define CRI_REG_BUILD_USER_2 15
#define CRI_REG_BUILD_USER_3 16
#define CRI_REG_N_CHANNELS 17
#define CRI_REG_TESTREG_DEVICE 18
#define CRI_REG_SC_REQ_CANCELED 19
#define CRI_REG_DMA_TX_TIMEOUT 20
#define CRI_REG_ILLEGAL_REQ 21
#define CRI_REG_MULTIDWREAD 22
#define CRI_REG_PCIE_CTRL 23
#define CRI_REG_APP_CFG 24
#define CRI_REG_APP_STS 25
#define CRI_REG_MC_CNT_CFG 26
#define CRI_REG_SYS_PERF_INT 27
#define CRI_REG_UNI_CFG 28
#define CRI_REG_PERF_PCI_NRDY 29
#define CRI_REG_PERF_PCI_TRANS 30
#define CRI_REG_PERF_PCI_MAX_NRDY 31
#define CRI_REG_PERF_CYCLE_CNT 32
#define CRI_REG_PERF_FIFO_FILL_0 33
#define CRI_REG_PERF_FIFO_FILL_1 34
#define CRI_REG_PERF_FIFO_FILL_2 35
#define CRI_REG_PERF_FIFO_FILL_3 36
#define CRI_REG_PERF_FIFO_FILL_4 37
#define CRI_REG_PERF_FIFO_FILL_5 38
#define CRI_REG_PERF_FIFO_FILL_6 39
#define CRI_REG_PERF_FIFO_FILL_7 40
#define CRI_REG_TEST_TIMEOUT 41
#define CRI_REG_EBDM_N_SG_CONFIG 0
#define CRI_REG_EBDM_BUFFER_SIZE_L 1
#define CRI_REG_EBDM_BUFFER_SIZE_H 2
#define CRI_REG_RBDM_N_SG_CONFIG 3
#define CRI_REG_RBDM_BUFFER_SIZE_L 4
#define CRI_REG_RBDM_BUFFER_SIZE_H 5
#define CRI_REG_EBDM_SW_READ_POINTER_L 6
#define CRI_REG_EBDM_SW_READ_POINTER_H 7
#define CRI_REG_RBDM_SW_READ_POINTER_L 8
#define CRI_REG_RBDM_SW_READ_POINTER_H 9
#define CRI_REG_DMA_CTRL 10
#define CRI_REG_PERF_N_EVENTS 11
#define CRI_REG_EBDM_FPGA_WRITE_POINTER_L 12
#define CRI_REG_EBDM_FPGA_WRITE_POINTER_H 13
#define CRI_REG_RBDM_FPGA_WRITE_POINTER_L 14
#define CRI_REG_RBDM_FPGA_WRITE_POINTER_H 15
#define CRI_REG_SGENTRY_ADDR_LOW 16
#define CRI_REG_SGENTRY_ADDR_HIGH 17
#define CRI_REG_SGENTRY_LEN 18
#define CRI_REG_SGENTRY_CTRL 19
#define CRI_REG_PERF_DMA_STALL 20
#define CRI_REG_MISC_CFG 21
#define CRI_REG_MISC_STS 22
#define CRI_REG_EBDM_OFFSET_L 23
#define CRI_REG_EBDM_OFFSET_H 24
#define CRI_REG_DESC_CNT_L 25
#define CRI_REG_DESC_CNT_H 26
#define CRI_REG_PERF_INTERVAL 27
#define CRI_REG_PERF_EBUF_STALL 28
#define CRI_REG_PERF_RBUF_STALL 29
#define CRI_REG_TESTREG_DMA 30
#define CRI_REG_TESTREG_DATA 0
#define CRI_REG_GTX_DATAPATH_CFG 1
