// Copyright 2012-2013 Jan de Cuveland <cmail@cuveland.de>

#include "Parameters.hpp"
#include "GitRevision.hpp"
#include "log.hpp"
#include <boost/program_options.hpp>
#include <iostream>

namespace po = boost::program_options;

void Parameters::parse_options(int argc, char* argv[]) {
  unsigned log_level = 2;
  unsigned log_syslog = 2;
  std::string log_file;

  po::options_description general("General options");
  auto general_add = general.add_options();
  general_add("version,V", "print version string");
  general_add("help,h", "produce help message");
  general_add("log-level,l",
              po::value<unsigned>(&log_level)
                  ->default_value(log_level)
                  ->value_name("<n>"),
              "set the file log level (all:0)");
  general_add("log-file,L", po::value<std::string>(&log_file), 
              "name of target log file");
  general_add("log-syslog,S",
              po::value<unsigned>(&log_syslog)
                  ->implicit_value(log_syslog)
                  ->value_name("<n>"),
              "enable logging to syslog at given log level");

  po::options_description archives("Input/Output archives");
  auto archives_add = archives.add_options();
  archives_add("input-archives,I", po::value<std::vector<std::string>>(&input_archives)
                                            ->multitoken()
                                            ->value_name("<space-separated-msa-files>"),
          "Paths to input microslice archives (.msa).");
  archives_add("output-archives,O", po::value<std::vector<std::string>>(&output_archives)
                                                ->multitoken()
                                                ->value_name("<space-separated-tsa-files>"),
            "Paths to output timeslice archives (.tsa).");

  po::options_description ts_parameters("Timeslice parameters");
  auto ts_parameters_add = ts_parameters.add_options();
  ts_parameters_add("timeslice-cnt", po::value<uint64_t>(&timeslice_cnt)
                                            ->default_value(0)
                                            ->value_name("<n>"),
              "Summed up amount of expected timeslices in the timeslice archives.");
  ts_parameters_add("timeslice-size", po::value<uint64_t>(&timeslice_size)
                                            ->value_name("<n>"),
              "Expected timeslice size.");
  ts_parameters_add("overlap", po::value<uint64_t>(&overlap)
                                      ->default_value(overlap)
                                      ->value_name("<n>"),
              "Timeslice overlap size.");

  po::options_description desc(
    "\nUsage:\n"
    "\tarchive_validator [options] -I input1.msa [ input2.msa ... ] -O output1.tsa [ output2.tsa ... ]\n\n"
    "This program checks if the output data was generated by the given input data.\n"
    "Output data is defined by timeslice archive files (*.tsa).\n"
    "Input data is defined by microslice archive files (*.msa)\n"
    "Use the 'timeslice parameters' to define the expected structure of the timeslices in the provided .tsa files"
    "\n\n"
    "Command line options");
  desc
    .add(general)
    .add(archives)
    .add(ts_parameters);

  po::variables_map vm;
  po::store(po::parse_command_line(argc, argv, desc), vm);
  po::notify(vm);

  if (vm.count("help") != 0u) {
    std::cout << "archive_validator, git revision " << g_GIT_REVISION << std::endl;
    std::cout << desc << std::endl;
    exit(EXIT_SUCCESS);
  }

  if (vm.count("version") != 0u) {
    std::cout << "archive_validator " << g_PROJECT_VERSION_GIT << ", git revision "
              << g_GIT_REVISION << std::endl;
    exit(EXIT_SUCCESS);
  }

  logging::add_console(static_cast<severity_level>(log_level));
  if (vm.count("log-file") != 0u) {
    L_(info) << "Logging output to " << log_file;
    logging::add_file(log_file, static_cast<severity_level>(log_level));
  }

  if (vm.count("log-syslog") != 0u) {
    logging::add_syslog(logging::syslog::local0,
                        static_cast<severity_level>(log_syslog));
  }

  validate = vm.count("input-archives") + vm.count("output-archives") > 0;
  
  bool analyze_parameter_set = true;
  if (vm.count("timeslice-cnt") == 0) {
    L_(fatal) << "'timeslice-cnt' option not set";
    analyze_parameter_set = false;
  }

  if (vm.count("timeslice-size") == 0) {
    L_(fatal) << "'timeslice-size' option not set";
    analyze_parameter_set = false;
  }

  if (vm.count("input-archives") == 0) {
    L_(fatal) << "'input-archives' option not set";
    analyze_parameter_set = false;
  }

  if (vm.count("output-archives") == 0) {
    L_(fatal) << "'output-archives' option not set";
    analyze_parameter_set = false;
  }

  if (!analyze_parameter_set) {
    throw ParametersException("Not all necessary parameters for archive analyzing are set.");
  }
}
