// rorc_registers.h: RORC Register Definitions
//
// Note:
// This file was automatically generated from:
// src/packages/registers.vhd
// Reposotory Revision: 918fc1ec957a54cafd793a0a0f578be02686181d
// Repository Status: dirty
// Build Timestamp: Fri Jan 17 19:43:06 CET 2014
#define RORC_C_BUILD_DATE 1389984186
#define RORC_C_BUILD_REVISION 0x918fc1ec957a54cafd793a0a0f578be02686181d
#define RORC_C_BUILD_STATUS_CLEAN 0
#define RORC_C_HARDWARE_VERSION 2
#define RORC_CHANNEL_OFFSET 0x00008000
#define RORC_DMA_CMP_SEL 13
#define RORC_REG_HARDWARE_INFO 0
#define RORC_REG_BUILD_FLAGS 1
#define RORC_REG_N_CHANNELS 2
#define RORC_REG_SC_REQ_CANCELED 3
#define RORC_REG_DMA_TX_TIMEOUT 4
#define RORC_REG_ILLEGAL_REQ 5
#define RORC_REG_MULTIDWREAD 6
#define RORC_REG_PCIE_CTRL 7
#define RORC_REG_PCIE_DST_BUSY 8
#define RORC_REG_MC_CNT_CFG 9
#define RORC_REG_DLM_CFG 10
#define RORC_REG_APP_CFG 11
#define RORC_REG_APP_STS 12
#define RORC_REG_BUILD_DATE_L 13
#define RORC_REG_BUILD_DATE_H 14
#define RORC_REG_BUILD_REV_0 15
#define RORC_REG_BUILD_REV_1 16
#define RORC_REG_BUILD_REV_2 17
#define RORC_REG_BUILD_REV_3 18
#define RORC_REG_BUILD_REV_4 19
#define RORC_REG_EBDM_N_SG_CONFIG 0
#define RORC_REG_EBDM_BUFFER_SIZE_L 1
#define RORC_REG_EBDM_BUFFER_SIZE_H 2
#define RORC_REG_RBDM_N_SG_CONFIG 3
#define RORC_REG_RBDM_BUFFER_SIZE_L 4
#define RORC_REG_RBDM_BUFFER_SIZE_H 5
#define RORC_REG_EBDM_SW_READ_POINTER_L 6
#define RORC_REG_EBDM_SW_READ_POINTER_H 7
#define RORC_REG_RBDM_SW_READ_POINTER_L 8
#define RORC_REG_RBDM_SW_READ_POINTER_H 9
#define RORC_REG_DMA_CTRL 10
#define RORC_REG_DMA_N_EVENTS_PROCESSED 11
#define RORC_REG_EBDM_FPGA_WRITE_POINTER_H 12
#define RORC_REG_EBDM_FPGA_WRITE_POINTER_L 13
#define RORC_REG_RBDM_FPGA_WRITE_POINTER_L 14
#define RORC_REG_RBDM_FPGA_WRITE_POINTER_H 15
#define RORC_REG_SGENTRY_ADDR_LOW 16
#define RORC_REG_SGENTRY_ADDR_HIGH 17
#define RORC_REG_SGENTRY_LEN 18
#define RORC_REG_SGENTRY_CTRL 19
#define RORC_REG_DMA_STALL_CNT 20
#define RORC_REG_MISC_CFG 21
#define RORC_REG_MISC_STS 22
#define RORC_REG_GTX_DATAPATH_CFG 0
#define RORC_REG_GTX_DATAPATH_STS 1
#define RORC_REG_GTX_MC_GEN_CFG 2
#define RORC_REG_GTX_PENDING_MC_L 3
#define RORC_REG_GTX_PENDING_MC_H 4
#define RORC_REG_GTX_CTRL_TX 5
#define RORC_REG_GTX_CTRL_RX 6
#define RORC_REG_GTX_DLM 7
#define RORC_REG_GTX_MC_GEN_CFG_HDR 8
#define RORC_REG_GTX_MC_GEN_CFG_IDX_L 9
#define RORC_REG_GTX_MC_GEN_CFG_IDX_H 10
#define RORC_REG_GTX_MC_INDEX_L 11
#define RORC_REG_GTX_MC_INDEX_H 12
#define RORC_MEM_BASE_CTRL_TX 16
#define RORC_MEM_SIZE_CTRL_TX 16
#define RORC_MEM_BASE_CTRL_RX 32
#define RORC_MEM_SIZE_CTRL_RX 16
