#!/usr/bin/env python3
"""Generate flesnet and SPM configurations."""

import os
import datetime
import sys

import flescfg


# global parameters, may be overwritten by environment
FLESNETDIR = os.getenv("FLESNETDIR", "/usr/bin/")
FLESCTLDIR = os.getenv("FLESCTLDIR", "/opt/fles/bin/")
RUNDIR = os.getenv("RUNDIR", "")
LOGDIR = os.getenv("LOGDIR", "log/")
SPM_CFG = os.getenv("SPM_CFG", os.path.join(RUNDIR, "readout.spm"))
TSMANAGER_CFG = os.getenv("TSMANAGER_CFG", os.path.join(RUNDIR, "tsmanager.cfg"))
STSERVER_CFG = os.getenv("STSERVER_CFG", os.path.join(RUNDIR, "stserver.cfg"))
TSBUILDER_CFG = os.getenv("TSBUILDER_CFG", os.path.join(RUNDIR, "tsbuilder.cfg"))

# Names both the timeslice buffer segment and the ipc endpoint the tsclients
# connect to, so it is the rendezvous point between tsbuilder and tsclient.
# The stserver segment needs no name, as nothing outside stserver opens it.
TS_SHM_ID = "flesnet_ts_builder"


def active_nodes(section: dict) -> dict:
    """Return only the nodes of a config section that are marked active."""
    return {
        node: nodeinfo
        for node, nodeinfo in section.items()
        if nodeinfo.get("active", True)
    }


def write_options(filename: str, config_file: str, options: dict) -> None:
    """Write a boost::program_options configuration file.

    Keys are translated to option names by replacing underscores with dashes.
    """
    with open(filename, "w", encoding="utf-8") as f:
        f.write(f"# Autogenerated from {config_file} at {datetime.datetime.now()}\n\n")
        for key, value in options.items():
            f.write(f"{key.replace('_', '-')} = {value}\n")


def env_prefix(nodeinfo: dict, **extra: str) -> str:
    """Return an env command prefix setting the per-node environment."""
    variables = dict(extra)
    if "ucx_net_devices" in nodeinfo:
        variables["UCX_NET_DEVICES"] = nodeinfo["ucx_net_devices"]
    if not variables:
        return ""
    assignments = " ".join(f"{key}={value}" for key, value in variables.items())
    return f"env {assignments} "


def consumers(common: dict, nodeinfo: dict) -> list[str]:
    """Return the tsclient parameter sets to start on a build node.

    The lists are kept separate in the configuration so that the individual
    groups can later be started and stopped independently, following the
    transitions of the ECS state machine. For now they are simply concatenated.
    """
    result = []
    for group in ("analyzers", "publishers", "recorders"):
        result += common[group] + nodeinfo.get(group, [])
    return result


def substitute(text: str, run_id: str, node: str, shm_id: str, client: int) -> str:
    """Expand the placeholders allowed in command parameters."""
    return (
        text.replace("%run_id%", run_id)
        .replace("%node%", node)
        .replace("%shm_id%", shm_id)
        .replace("%client%", str(client))
    )


def main(config_file: str, run_id: str):
    """Generate flesnet and SPM configurations."""
    # load the config file
    config = flescfg.load(config_file)
    if config is None:
        print("Error loading configuration file.")
        sys.exit(1)

    common = config["common"]
    manager = config["manager_node"]
    entry_nodes = active_nodes(config["entry_nodes"])
    build_nodes = active_nodes(config["build_nodes"])

    print(
        "Generating configs for", manager["name"], list(entry_nodes), list(build_nodes)
    )
    print("Writing output to", SPM_CFG)

    # timeslice duration is used by both the tsmanager and the stservers and
    # has to be identical for both, so it is written from a single setting
    write_options(
        TSMANAGER_CFG,
        config_file,
        {"timeslice_duration": common["timeslice_duration"], **common["tsmanager"]},
    )
    write_options(
        STSERVER_CFG,
        config_file,
        {
            "tsmanager_address": manager["address"],
            "timeslice_duration": common["timeslice_duration"],
            **common["stserver"],
        },
    )
    write_options(
        TSBUILDER_CFG,
        config_file,
        {
            "tsmanager_address": manager["address"],
            "shm_id": TS_SHM_ID,
            **common["tsbuilder"],
        },
    )

    # The four roles find each other through the tsmanager and retry until it
    # answers, so no startup ordering has to be enforced here.

    # manager node
    mn_spm = [
        f"{manager['name']}: {env_prefix(manager)}{FLESNETDIR}tsmanager"
        f" -c {TSMANAGER_CFG} -L {LOGDIR}{manager['name']}_tsmanager.log --log-syslog"
    ]

    # entry nodes
    # fles_input.py configures the CRIs and only then starts the stserver, which
    # picks up the enabled channels once at startup.
    en_spm = [
        f"{node}: env LOGDIR={LOGDIR}{node}_ STSERVER_CFG={STSERVER_CFG}"
        f" {os.path.join(FLESCTLDIR, 'fles_input.py')} {config_file} {node}"
        for node in entry_nodes
    ]

    # build nodes
    bn_spm = []
    for node, nodeinfo in build_nodes.items():
        bn_spm.append(
            f"{node}: {env_prefix(nodeinfo)}{FLESNETDIR}tsbuilder"
            f" -c {TSBUILDER_CFG} -L {LOGDIR}{node}_tsbuilder.log --log-syslog"
        )
        for client, param in enumerate(consumers(common, nodeinfo)):
            param = substitute(param, run_id, node, TS_SHM_ID, client)
            bn_spm.append(
                f"{node}: {FLESNETDIR}tsclient -c{client}"
                f" -L {LOGDIR}{node}_{client}_tsclient.log --log-syslog {param}"
            )
        for cmd in common["extra_cmd"] + nodeinfo.get("extra_cmd", []):
            bn_spm.append(f"{node}: {substitute(cmd, run_id, node, TS_SHM_ID, 0)}")

    with open(SPM_CFG, "w", encoding="utf-8") as f:
        f.write(
            f"# SPM configuration autogenerated from {config_file} at {datetime.datetime.now()}\n"
        )
        f.write("\n# Manager node\n")
        f.write("\n".join(mn_spm) + "\n")
        f.write("\n# Entry nodes\n")
        f.write("\n".join(en_spm) + "\n")
        f.write("\n# Build nodes\n")
        f.write("\n".join(bn_spm) + "\n")


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Generate flesnet and SPM configurations."
    )
    parser.add_argument("config", help="Path to the configuration file")
    parser.add_argument("run_id", help="Run ID")
    args = parser.parse_args()
    main(args.config, args.run_id)
